export const TICKETS_MICROSERVICE_PROVIDER = 'TICKETS_MICROSERVICE';
export const AUTH_MICROSERVICE_PROVIDER = 'AUTH_MICROSERVICE';
export const ORDERS_MICROSERVICE_PROVIDER = 'ORDERS_MICROSERVICE';
export const PAYMENTS_MICROSERVICE_PROVIDER = 'PAYMENTS_MICROSERVICE';
